const CONTRIBUTORS: &str = r#"
avinassh (@avinassh)
b3nj5m1n (@b3nj5m1n)
bl-ue (@bl-ue)
Benjamin Vergnaud (@bvergnaud)
Brad Robel-Forrest (@bradrf)
Bruce Huang (@helbing)
c-14 (@c-14)
ConradLudate (@conradludgate)
CosmicHorror  (@LovecraftianHorror)
Daniel (@daniel0611)
DanielAtCosmicDNA (@DanielAtCosmicDNA)
Ellie Huxtable (@ellie)
Eric Crosson (@EricCrosson)
Frank Hamand (@frankh)
Herby Gillot (@herbygillot)
Ian Smith (@ismith)
Ilkin Bayramli (@ibayramli)
Jakob Schrettenbrunner (@schrej)
Jakub Jirutka (@jirutka)
Jakub Panek (@panekj)
Jamie Quigley (@Sciencentistguy)
Jannik (@mozzieongit)
jean-santos (@jean-santos)
Jerome Ducret (@DucretJe)
Klas Mellbourn (@Mellbourn)
Laurent le Beau-Martin (@laurentlbm)
lchausmann (@lchausmann)
Lucas Burns (@lmburns)
Lucy (@Absolucy)
Luke Baker (@lukebaker)
Manel Vilar (@manelvf)
Mark Wotton (@mwotton)
Martin Indra  (@Indy2222)
Mat Jones (@mrjones2014)
mb6ockatf (@mb6ockatf)
Michael Bianco (@iloveitaly)
Michael Mior (@michaelmior)
morguldir (@morguldir)
mundry (@mundry)
networkException (@networkException)
Noyzen (@noyez)
Omer Katz (@thedrow)
Orhun Parmaksız (@orhun)
Patrick (@pmarschik)
Patrick Jackson (@patricksjackson)
Plamen Dimitrov (@pevogam)
Sam Edwards  (@dotsam)
Sam Lanning (@s0)
Sandro (@SuperSandro2000)
Satyarth Sampath (@notsatyarth)
Simon Elsbrock (@elsbrock)
TymanWasTaken  (@TymanWasTaken)
Ubiquitous Photon  (@UbiquitousPhoton)
Violet (@shreve)
Will Fancher (@ElvishJerricco)
wpbrz (@wpbrz)
xfzv (@xfzv)
Yuvi Panda (@yuvipanda)
ZhiHong Li (@OnePieceJoker)
"#;

pub fn run() {
    println!("{}", CONTRIBUTORS);
}
