const CONTRIBUTORS: &str = r#"
Ellie Huxtable (@ellie)
ConradLudate (@conradludgate)
Orhun Parmaksız (@orhun)
Jamie Quigley (@Sciencentistguy)
Yuvi Panda (@yuvipanda)
Jakub Jirutka (@jirutka)
Frank Hamand (@frankh)
Jannik (@mozzieongit)
Sandro (@SuperSandro2000)
bl-ue (@bl-ue)
Ian Smith (@ismith)
Michael Bianco (@iloveitaly)
Mat Jones (@mrjones2014)
Mark Wotton (@mwotton)
Jakob Schrettenbrunner (@schrej)
Jakub Panek (@panekj)
ZhiHong Li (@OnePieceJoker)
Satyarth Sampath (@notsatyarth)
Noyzen (@noyez)
Jerome Ducret (@DucretJe)
c-14 (@c-14)
avinassh (@avinassh)
Will Fancher (@ElvishJerricco)
Omer Katz (@thedrow)
Manel Vilar (@manelvf)
Simon Elsbrock (@elsbrock)
Patrick Jackson (@patricksjackson)
Lucas Burns (@lmburns)
Patrick (@pmarschik)
Herby Gillot (@herbygillot)
Brad Robel-Forrest (@bradrf)
lchausmann (@lchausmann)
mundry (@mundry)
jean-santos (@jean-santos)
networkException (@networkException)
mb6ockatf (@mb6ockatf)
Luke Baker (@lukebaker)
Daniel (@daniel0611)
Ubiquitous Photon  (@UbiquitousPhoton)
Sam Lanning (@s0)
b3nj5m1n (@b3nj5m1n)
Sam Edwards  (@dotsam)
Ilkin Bayramli (@ibayramli)
Klas Mellbourn (@Mellbourn)
morguldir (@morguldir)
Martin Indra  (@Indy2222)
Michael Mior (@michaelmior)
CosmicHorror  (@LovecraftianHorror)
Laurent le Beau-Martin (@laurentlbm)"#;

pub fn run() {
    println!("{}", CONTRIBUTORS);
}
