[package]
name = "atuin-daemon"
edition = "2024"
version = { workspace = true }
description = "The daemon crate for Atuin"

authors.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atuin-client = { workspace = true }
parking_lot = { workspace = true }
atuin-domain = { workspace = true }
enum_dispatch = { workspace = true }
derive_more = { workspace = true }
thiserror = { workspace = true }
atuin-dotfiles = { workspace = true }
atuin-history = { workspace = true }

time = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
eyre = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
reqwest = { workspace = true }

dashmap = { workspace = true }
lasso = { workspace = true }
tonic-types = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tokio-stream = { workspace = true, features = ["sync"] }
futures = { workspace = true }
hyper-util = { workspace = true }

rand.workspace = true
frizbee = { workspace = true }
easy-cast = { workspace = true }

[dependencies.atuin-common]
workspace = true
features = ["os"]

[target.'cfg(target_os = "linux")'.dependencies]
listenfd = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
rstest = { workspace = true }
proptest = { workspace = true }

[build-dependencies]
protox = { workspace = true }
tonic-build = { workspace = true }
tonic-prost-build = { workspace = true }

[lints]
workspace = true
