apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: atuin
    newName: ghcr.io/ellie/atuin
    newTag: 15.0.0

resources:
  - atuin.yaml

configMapGenerator:
  - name: atuin
    literals:
    - open_registration=true
  - name: database

secretGenerator:
  - name: database
