[package]
name = "atuin-history"
description = "The history crate for Atuin"
edition = "2024"

authors.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
atuin-client = { workspace = true }

crossterm = { workspace = true, features = ["use-dev-tty"] }
easy-cast = { workspace = true }
serde = { workspace = true }
time = { workspace = true }
unicode-segmentation = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
rand = { workspace = true }
rstest = { workspace = true }

[[bench]]
name = "smart_sort"
harness = false

[lints]
workspace = true
