[package]
name = "atuin-history"
description = "The history crate for Atuin"
edition = "2024"
version = { workspace = true }

authors.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atuin-client = { workspace = true }

time = { workspace = true }
serde = { workspace = true }
crossterm = { workspace = true, features = ["use-dev-tty"] }
unicode-segmentation = { workspace = true }
easy-cast = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
rand = { workspace = true }
rstest = { workspace = true }

[[bench]]
name = "smart_sort"
harness = false

[lints]
workspace = true
