[package]
name = "atuin-scripts"
edition = "2024"
description = "The scripts crate for Atuin"

authors.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
atuin-client = { workspace = true }
atuin-common = { workspace = true, features = ["sqlite"] }
atuin-domain = { workspace = true }

derive_more = { workspace = true }
easy-cast = { workspace = true }
eyre = { workspace = true }
minijinja = { workspace = true }
pretty_assertions = { workspace = true }
rmp = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sql-builder = { workspace = true }
sqlx = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
typed-builder = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[lints]
workspace = true
