[package]
name = "atuin-api-client"
edition = "2024"
description = "Low-level clients for the Atuin APIs"

authors.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
atuin-domain = { workspace = true }

derive_more = { workspace = true }
parking_lot = { workspace = true }
progenitor-client = { workspace = true }
reqwest = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
openapiv3 = { workspace = true }
progenitor-impl = { workspace = true }
quote = { workspace = true }
schemars08 = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
rstest = { workspace = true }
wiremock = { workspace = true }

[lints]
workspace = true
