[package]
name = "atuin-api-client"
edition = "2024"
description = "Low-level clients for the Atuin APIs"

authors.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true
