apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atuin

labels:
  - pairs:
      app: atuin
    includeSelectors: true

configMapGenerator:
  - name: atuin
    envs:
      - config/atuin.env

secretGenerator:
  - name: atuin
    envs:
      - secrets/atuin.env

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
