[package]
name = "atuin-pty-proxy"
edition = "2024"
description = "a PTY proxy for atuin"

authors.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
clap = { workspace = true }
easy-cast = { workspace = true }

[target.'cfg(unix)'.dependencies]
atuin-client = { workspace = true }
atuin-common = { workspace = true, features = ["ansi", "os"] }
atuin-vt100 = { workspace = true }
crossterm = { workspace = true }
eyre = { workspace = true }
portable-pty = { workspace = true }
signal-hook = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[lints]
workspace = true
