apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atuin
spec:
  rules:
    - host: atuin.example.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: atuin
                port:
                  name: http
