[package]
name = "atuin-common"
edition = "2024"
description = "common library for atuin"

authors.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
test-utils = ["dep:tracing-subscriber"]
unicode = ["dep:unicode-width", "dep:unicode-segmentation"]
ansi = ["dep:atuin-vt100"]
os = ["dep:rustix", "dep:windows-sys"]
db = ["dep:sqlx"]
sqlite = ["db", "sqlx/sqlite", "sqlx/regexp", "dep:libsqlite3-sys", "dep:tokio-util"]

[dependencies]
atuin-vt100 = { workspace = true, optional = true }

base64 = { workspace = true }
crypto_secretbox = { workspace = true }
derive_more = { workspace = true }
directories = { workspace = true }
easy-cast = { workspace = true }
eyre = { workspace = true }
fs-err = { workspace = true }
futures = { workspace = true }
getrandom = { workspace = true }
itertools = { workspace = true }
libsqlite3-sys = { workspace = true, optional = true }
parking_lot = { workspace = true }
rmp = { workspace = true }
rusty_paserk = { workspace = true }
rusty_paseto = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
sqlx = { workspace = true, optional = true }
sysinfo = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["formatting", "parsing"] }
tiny-bip39 = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, optional = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }
unicode-segmentation = { workspace = true, optional = true }
unicode-width = { workspace = true, optional = true }
url = { workspace = true }
uuid = { workspace = true }
zeroize = { workspace = true }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
proptest = { workspace = true }
rstest = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
