[package]
name = "atuin-common"
edition = "2024"
description = "common library for atuin"

rust-version = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test-utils = ["dep:tracing-subscriber"]
unicode = ["dep:unicode-width", "dep:unicode-segmentation"]
ansi = ["dep:atuin-vt100"]
os = ["dep:rustix"]
sqlite = ["dep:sqlx", "dep:libsqlite3-sys", "dep:tokio-util"]

[dependencies]
atuin-vt100 = { workspace = true, optional = true }
derive_more = { workspace = true }
tiny-bip39 = { workspace = true }
crypto_secretbox = { workspace = true }
time = { workspace = true, features = ["formatting", "parsing"] }
serde = { workspace = true }
serde_with = "3.8.1"
uuid = { workspace = true }
eyre = { workspace = true }
url = { workspace = true }
thiserror = { workspace = true }
directories = { workspace = true }
sysinfo = "0.30.7"
base64 = { workspace = true }
getrandom = "0.4"
tracing = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }
unicode-width = { version = "0.2", optional = true }
unicode-segmentation = { version = "1.11.0", optional = true }
itertools = { workspace = true }
rusty_paseto = { workspace = true }
rusty_paserk = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, optional = true }
parking_lot = { workspace = true }
futures = "0.3"
serde_json = { workspace = true }
zeroize = { workspace = true }
rmp = { workspace = true }
fs-err = { workspace = true }
semver = { workspace = true }
sqlx = { workspace = true, features = ["sqlite", "regexp"], optional = true }
libsqlite3-sys = { workspace = true, optional = true }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
proptest = { workspace = true }
rstest = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
