// @generated by crates/atuin-api-client/codegen from openapi.json. Do not edit.

#[allow(unused_imports)]
pub use progenitor_client::{ByteStream, ClientInfo, Error, ResponseValue};
#[allow(unused_imports)]
use progenitor_client::{encode_path, ClientHooks, OperationInfo, RequestBuilderExt};
/// Types used as operation parameters and responses.
#[allow(clippy::all)]
pub mod types {
    ///`AiErrorResponse`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct AiErrorResponse {
        pub error: ::std::string::String,
        pub message: ::std::string::String,
    }
    ///`CapabilitiesResponse`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct CapabilitiesResponse {
        pub capabilities: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
        pub version: ::std::string::String,
    }
    ///`ChangePasswordRequest`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ChangePasswordRequest {
        pub current_password: crate::Secret,
        pub new_password: crate::Secret,
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub totp_code: ::std::option::Option<crate::Secret>,
    }
    ///`CliCodeResponse`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct CliCodeResponse {
        pub code: crate::Secret,
    }
    ///`CliVerifyResponse`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct CliVerifyResponse {
        pub success: bool,
        pub token: crate::Secret,
    }
    ///`CurrentUser`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct CurrentUser {
        pub orgs: ::std::vec::Vec<CurrentUserOrgsItem>,
        pub user: CurrentUserUser,
    }
    ///`CurrentUserOrgsItem`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct CurrentUserOrgsItem {
        pub avatar_url: ::std::string::String,
        pub id: ::uuid::Uuid,
        #[serde(deserialize_with = "::std::option::Option::deserialize")]
        pub name: ::std::option::Option<::std::string::String>,
        pub slug: ::std::string::String,
    }
    ///`CurrentUserUser`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct CurrentUserUser {
        pub avatar_url: ::std::string::String,
        #[serde(deserialize_with = "::std::option::Option::deserialize")]
        pub display_name: ::std::option::Option<::std::string::String>,
        pub id: ::uuid::Uuid,
        pub username: ::std::string::String,
    }
    ///`DeleteUserRequest`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct DeleteUserRequest {
        pub password: crate::Secret,
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub totp_code: ::std::option::Option<crate::Secret>,
    }
    ///`ErrorResponse`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ErrorResponse {
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub code: ::std::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub error: ::std::option::Option<::std::string::String>,
        #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
        pub errors: ::std::vec::Vec<::std::string::String>,
        pub reason: ::std::string::String,
    }
    ///`IndexResponse`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct IndexResponse {
        pub homage: ::std::string::String,
        pub version: ::std::string::String,
    }
    ///`LinkAccountRequest`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct LinkAccountRequest {
        pub token: crate::Secret,
    }
    ///`LoginRequest`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct LoginRequest {
        pub password: crate::Secret,
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub totp_code: ::std::option::Option<crate::Secret>,
        pub username: ::std::string::String,
    }
    ///`LoginResponse`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct LoginResponse {
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub auth: ::std::option::Option<::std::string::String>,
        pub session: crate::Secret,
    }
    ///`MeResponse`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct MeResponse {
        #[serde(deserialize_with = "::std::option::Option::deserialize")]
        pub username: ::std::option::Option<::std::string::String>,
    }
    ///`ModelInfo`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ModelInfo {
        pub alias: ::std::string::String,
        pub description: ::std::string::String,
        pub name: ::std::string::String,
    }
    ///`ModelList`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ModelList {
        pub default: ::std::string::String,
        pub models: ::std::vec::Vec<ModelInfo>,
    }
    ///`PackfileConfirmResponse`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct PackfileConfirmResponse {
        pub status: ::std::string::String,
    }
    ///`PackfileCreateRequest`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct PackfileCreateRequest {
        pub manifest_id: ::uuid::Uuid,
        pub packfile_size_bytes: u64,
        #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
        pub records: ::std::vec::Vec<::uuid::Uuid>,
    }
    ///`PackfileDownloadResponse`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct PackfileDownloadResponse {
        pub download_url: ::url::Url,
    }
    ///`PackfileResponse`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct PackfileResponse {
        pub packfile_id: ::uuid::Uuid,
        pub upload_url: ::url::Url,
    }
    ///`RegisterRequest`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct RegisterRequest {
        pub email: ::std::string::String,
        pub password: crate::Secret,
        pub username: ::std::string::String,
    }
    ///`RegisterResponse`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct RegisterResponse {
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub auth: ::std::option::Option<::std::string::String>,
        pub session: crate::Secret,
    }
    ///`UsageBucket`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct UsageBucket {
        pub limit: i64,
        pub used: u64,
    }
    ///`UsageSnapshot`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct UsageSnapshot {
        pub input: UsageBucket,
        pub output: UsageBucket,
        pub period: ::std::string::String,
        pub requests: UsageBucket,
        pub resets_at: crate::DateTime,
    }
    ///`UserResponse`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct UserResponse {
        pub username: ::std::string::String,
    }
    /// Error types.
    pub mod error {
        /// Error from a `TryFrom` or `FromStr` implementation.
        pub struct ConversionError(::std::borrow::Cow<'static, str>);
        impl ::std::error::Error for ConversionError {}
        impl ::std::fmt::Display for ConversionError {
            fn fmt(
                &self,
                f: &mut ::std::fmt::Formatter<'_>,
            ) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Display::fmt(&self.0, f)
            }
        }
        impl ::std::fmt::Debug for ConversionError {
            fn fmt(
                &self,
                f: &mut ::std::fmt::Formatter<'_>,
            ) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Debug::fmt(&self.0, f)
            }
        }
        impl From<&'static str> for ConversionError {
            fn from(value: &'static str) -> Self {
                Self(value.into())
            }
        }
        impl From<String> for ConversionError {
            fn from(value: String) -> Self {
                Self(value.into())
            }
        }
    }
}
#[derive(Clone, Debug)]
/**Client for Atuin

Version: 1.0.0*/
pub struct Client {
    pub(crate) baseurl: String,
    pub(crate) client: reqwest::Client,
    pub(crate) inner: crate::HookState,
}
impl Client {
    /// Create a new client.
    ///
    /// `baseurl` is the base URL provided to the internal
    /// `reqwest::Client`, and should include a scheme and hostname,
    /// as well as port and a path stem if applicable.
    pub fn new(baseurl: &str, inner: crate::HookState) -> Self {
        #[cfg(not(target_arch = "wasm32"))]
        let client = {
            let dur = ::std::time::Duration::from_secs(15u64);
            reqwest::ClientBuilder::new().connect_timeout(dur).timeout(dur)
        };
        #[cfg(target_arch = "wasm32")]
        let client = reqwest::ClientBuilder::new();
        Self::new_with_client(baseurl, client.build().unwrap(), inner)
    }
    /// Construct a new client with an existing `reqwest::Client`,
    /// allowing more control over its configuration.
    ///
    /// `baseurl` is the base URL provided to the internal
    /// `reqwest::Client`, and should include a scheme and hostname,
    /// as well as port and a path stem if applicable.
    pub fn new_with_client(
        baseurl: &str,
        client: reqwest::Client,
        inner: crate::HookState,
    ) -> Self {
        Self {
            baseurl: baseurl.to_string(),
            client,
            inner,
        }
    }
}
impl ClientInfo<crate::HookState> for Client {
    fn api_version() -> &'static str {
        "1.0.0"
    }
    fn baseurl(&self) -> &str {
        self.baseurl.as_str()
    }
    fn client(&self) -> &reqwest::Client {
        &self.client
    }
    fn inner(&self) -> &crate::HookState {
        &self.inner
    }
}
impl ClientHooks<crate::HookState> for &Client {}
#[allow(clippy::all)]
impl Client {
    /**Sends a `GET` request to `/`

*/
    pub async fn get_index<'a>(
        &'a self,
    ) -> Result<ResponseValue<types::IndexResponse>, Error<()>> {
        let url = format!("{}/", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_index",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `DELETE` request to `/account`

*/
    pub async fn legacy_delete_account<'a>(
        &'a self,
        body: &'a types::DeleteUserRequest,
    ) -> Result<
        ResponseValue<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
        Error<()>,
    > {
        let url = format!("{}/account", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .delete(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "legacy_delete_account",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `PATCH` request to `/account/password`

*/
    pub async fn legacy_change_password<'a>(
        &'a self,
        body: &'a types::ChangePasswordRequest,
    ) -> Result<
        ResponseValue<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
        Error<()>,
    > {
        let url = format!("{}/account/password", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .patch(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "legacy_change_password",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `GET` request to `/api/cli/models`

*/
    pub async fn list_models<'a>(
        &'a self,
    ) -> Result<ResponseValue<types::ModelList>, Error<()>> {
        let url = format!("{}/api/cli/models", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "list_models",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `GET` request to `/api/cli/usage`

*/
    pub async fn get_usage<'a>(
        &'a self,
    ) -> Result<ResponseValue<types::UsageSnapshot>, Error<()>> {
        let url = format!("{}/api/cli/usage", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_usage",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `GET` request to `/api/me`

*/
    pub async fn get_current_user<'a>(
        &'a self,
    ) -> Result<ResponseValue<types::CurrentUser>, Error<()>> {
        let url = format!("{}/api/me", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_current_user",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `DELETE` request to `/api/v0/account`

*/
    pub async fn delete_account<'a>(
        &'a self,
        body: &'a types::DeleteUserRequest,
    ) -> Result<
        ResponseValue<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
        Error<()>,
    > {
        let url = format!("{}/api/v0/account", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .delete(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "delete_account",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `POST` request to `/api/v0/account/link`

*/
    pub async fn link_account<'a>(
        &'a self,
        body: &'a types::LinkAccountRequest,
    ) -> Result<ResponseValue<()>, Error<()>> {
        let url = format!("{}/api/v0/account/link", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self.client.post(url).json(&body).headers(header_map).build()?;
        let info = OperationInfo {
            operation_id: "link_account",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => Ok(ResponseValue::empty(response)),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `PATCH` request to `/api/v0/account/password`

*/
    pub async fn change_password<'a>(
        &'a self,
        body: &'a types::ChangePasswordRequest,
    ) -> Result<
        ResponseValue<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
        Error<()>,
    > {
        let url = format!("{}/api/v0/account/password", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .patch(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "change_password",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `GET` request to `/api/v0/capabilities`

*/
    pub async fn get_capabilities<'a>(
        &'a self,
    ) -> Result<ResponseValue<types::CapabilitiesResponse>, Error<()>> {
        let url = format!("{}/api/v0/capabilities", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_capabilities",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `POST` request to `/api/v0/login`

*/
    pub async fn login<'a>(
        &'a self,
        body: &'a types::LoginRequest,
    ) -> Result<ResponseValue<types::LoginResponse>, Error<()>> {
        let url = format!("{}/api/v0/login", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "login",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `GET` request to `/api/v0/me`

*/
    pub async fn get_me<'a>(
        &'a self,
    ) -> Result<ResponseValue<types::MeResponse>, Error<()>> {
        let url = format!("{}/api/v0/me", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_me",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `POST` request to `/api/v0/packfiles`

*/
    pub async fn create_packfile<'a>(
        &'a self,
        body: &'a types::PackfileCreateRequest,
    ) -> Result<ResponseValue<types::PackfileResponse>, Error<()>> {
        let url = format!("{}/api/v0/packfiles", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "create_packfile",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `GET` request to `/api/v0/packfiles/{manifest_id}`

*/
    pub async fn get_packfile<'a>(
        &'a self,
        manifest_id: &'a ::uuid::Uuid,
    ) -> Result<ResponseValue<types::PackfileDownloadResponse>, Error<()>> {
        let url = format!(
            "{}/api/v0/packfiles/{}", self.baseurl, encode_path(& manifest_id
            .to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_packfile",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `POST` request to `/api/v0/packfiles/{manifest_id}/confirm`

*/
    pub async fn confirm_packfile<'a>(
        &'a self,
        manifest_id: &'a ::uuid::Uuid,
    ) -> Result<ResponseValue<types::PackfileConfirmResponse>, Error<()>> {
        let url = format!(
            "{}/api/v0/packfiles/{}/confirm", self.baseurl, encode_path(& manifest_id
            .to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "confirm_packfile",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `GET` request to `/api/v0/record`

*/
    pub async fn get_record_status<'a>(
        &'a self,
    ) -> Result<ResponseValue<::atuin_domain::record::RecordStatus>, Error<()>> {
        let url = format!("{}/api/v0/record", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_record_status",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `POST` request to `/api/v0/record`

*/
    pub async fn post_records<'a>(
        &'a self,
        body: &'a ::std::vec::Vec<
            ::atuin_domain::record::Record<::atuin_domain::record::EncryptedData>,
        >,
    ) -> Result<ResponseValue<()>, Error<()>> {
        let url = format!("{}/api/v0/record", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self.client.post(url).json(&body).headers(header_map).build()?;
        let info = OperationInfo {
            operation_id: "post_records",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => Ok(ResponseValue::empty(response)),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `GET` request to `/api/v0/record/next`

*/
    pub async fn get_next_records<'a>(
        &'a self,
        count: &'a u64,
        host: &'a ::uuid::Uuid,
        start: Option<&'a u64>,
        tag: &'a str,
    ) -> Result<
        ResponseValue<
            ::std::vec::Vec<
                ::atuin_domain::record::Record<::atuin_domain::record::EncryptedData>,
            >,
        >,
        Error<()>,
    > {
        let url = format!("{}/api/v0/record/next", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .query(&progenitor_client::QueryParam::new("count", &count))
            .query(&progenitor_client::QueryParam::new("host", &host))
            .query(&progenitor_client::QueryParam::new("start", &start))
            .query(&progenitor_client::QueryParam::new("tag", &tag))
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_next_records",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `POST` request to `/api/v0/register`

*/
    pub async fn register<'a>(
        &'a self,
        body: &'a types::RegisterRequest,
    ) -> Result<ResponseValue<types::RegisterResponse>, Error<()>> {
        let url = format!("{}/api/v0/register", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "register",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `DELETE` request to `/api/v0/store`

*/
    pub async fn delete_store<'a>(&'a self) -> Result<ResponseValue<()>, Error<()>> {
        let url = format!("{}/api/v0/store", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self.client.delete(url).headers(header_map).build()?;
        let info = OperationInfo {
            operation_id: "delete_store",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => Ok(ResponseValue::empty(response)),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `POST` request to `/auth/cli/code`

*/
    pub async fn create_cli_auth_code<'a>(
        &'a self,
    ) -> Result<ResponseValue<types::CliCodeResponse>, Error<()>> {
        let url = format!("{}/auth/cli/code", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "create_cli_auth_code",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `POST` request to `/auth/cli/verify`

*/
    pub async fn verify_cli_auth_code<'a>(
        &'a self,
        code: &'a crate::Secret,
    ) -> Result<ResponseValue<types::CliVerifyResponse>, Error<()>> {
        let url = format!("{}/auth/cli/verify", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .query(&progenitor_client::QueryParam::new("code", &code))
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "verify_cli_auth_code",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `POST` request to `/login`

*/
    pub async fn legacy_login<'a>(
        &'a self,
        body: &'a types::LoginRequest,
    ) -> Result<ResponseValue<types::LoginResponse>, Error<()>> {
        let url = format!("{}/login", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "legacy_login",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `POST` request to `/register`

*/
    pub async fn legacy_register<'a>(
        &'a self,
        body: &'a types::RegisterRequest,
    ) -> Result<ResponseValue<types::RegisterResponse>, Error<()>> {
        let url = format!("{}/register", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "legacy_register",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Sends a `GET` request to `/user/{username}`

*/
    pub async fn legacy_get_user<'a>(
        &'a self,
        username: &'a str,
    ) -> Result<ResponseValue<types::UserResponse>, Error<()>> {
        let url = format!(
            "{}/user/{}", self.baseurl, encode_path(& username.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map
            .append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(Self::api_version()),
            );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "legacy_get_user",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => ResponseValue::from_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
}
/// Items consumers will typically use such as the Client.
pub mod prelude {
    #[allow(unused_imports)]
    pub use super::Client;
}
