[package]
name = "atuin-dotfiles"
description = "The dotfiles crate for Atuin"
edition = "2024"

authors.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
atuin-client = { workspace = true }
atuin-common = { workspace = true }
atuin-domain = { workspace = true }

crypto_secretbox = { workspace = true }
derive_more = { workspace = true }
eyre = { workspace = true }
rand = { workspace = true }
rmp = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[lints]
workspace = true
