apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atuin

labels:
  - pairs:
      app: atuin
    includeSelectors: true

configMapGenerator:
  - name: atuin
    behavior: replace
    envs:
      - config/atuin.env

patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Secret
      metadata:
        name: atuin
  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0
        value:
          name: atuin-data
          persistentVolumeClaim:
            claimName: atuin-data
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/0/subPath
        value: atuin/config
    target:
      kind: Deployment
      name: atuin

resources:
  - ../../base
  - nfs-pv.yml
  - nfs-pvc.yml
  - ingress.yaml
  - serviceaccount.yaml
  - secrets.yaml
