apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atuin-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  volumeName: atuin-data
  storageClassName: nfs-csi
