---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: atuin
spec:
  provider:
    vault:
      server: https://some.vault.com
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: k8s-mount-path
          role: atuin
          serviceAccountRef:
            name: atuin
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atuin
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: atuin
    kind: SecretStore
  target:
    name: atuin
    creationPolicy: Owner
  data:
    - secretKey: ATUIN_DB_URI
      remoteRef:
        key: atuin
        property: ATUIN_DB_URI
