// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=src/db/postgres/migrations");
    println!("cargo:rerun-if-changed=src/db/sqlite/migrations");
    println!("cargo:rerun-if-changed=src/db/mysql/migrations");
}
