name: Deploy release docs

on:
  push:
    tags:
      - "v*"

concurrency:
  group: docs-pages
  cancel-in-progress: false

jobs:
  stable:
    if: ${{ !contains(github.ref_name, '-') }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      MKDOCS_GIT_COMMITTERS_ENABLED: true
      MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/actions/docs-setup
      - uses: ./.github/actions/docs-deploy-stable
        with:
          version: ${{ github.ref_name }}
      - uses: ./.github/actions/docs-root-files

  prerelease:
    if: ${{ contains(github.ref_name, '-') }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      MKDOCS_GIT_COMMITTERS_ENABLED: true
      MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/actions/docs-setup
      - uses: ./.github/actions/docs-deploy-prerelease
        with:
          version: ${{ github.ref_name }}
      - uses: ./.github/actions/docs-root-files
