# Verify the Nix build is working
# Failures will usually occur due to an out of date Rust version
# That can be updated to the latest version in nixpkgs-unstable with `nix flake update`
name: Nix
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'ui/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'ui/**'

permissions:
  contents: read

jobs:
  check:
    runs-on: depot-ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0

      - name: Run nix flake check
        run: nix flake check --print-build-logs

  build-test:
    runs-on: depot-ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0

      - name: Run nix build
        run: nix build --print-build-logs

  nixfmt:
    runs-on: depot-ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0

      # Run `nix fmt` to fix any failures here
      - name: Check nix formatting
        run: nix fmt -- --check $(git ls-files '*.nix')
