name: Rust

on:
  push:
    branches: [main]
    paths-ignore:
      - "ui/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "ui/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [depot-ubuntu-24.04, depot-macos-26, depot-windows-2025-16]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - name: Install OpenSSL dev libraries (Linux)
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@v1.6.3
        with:
          packages: libssl-dev pkg-config
          version: 1.0

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.98.0

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo build common
        run: cargo build -p atuin-common --locked --release

      - name: Run cargo build client
        run: cargo build -p atuin-client --locked --release

      - name: Run cargo build server
        run: cargo build -p atuin-server --locked --release

      - name: Run cargo build main
        run: cargo build --all --locked --release

  # This used to use cross compilling via `cross` but it's more reliable to just
  # run this on a real illumos (OmniOS) system.
  test-in-vm:
    name: Test in VM (illumos)
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Test on illumos
        uses: vmactions/omnios-vm@027e3ec08fed6fb740ab5f300c2605f9de02997a # v1.3.4
        with:
          # use the latest omnios LTS
          release: "r151054-build"
          envs: "CARGO_TERM_COLOR"
          usesh: true
          mem: 4096
          copyback: false
          prepare: |
            pkg install pkg-config openssl
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.98.0
          run: |
            . "$HOME/.cargo/env"

            banner client
            cargo build -p atuin-client --locked --release

            banner server
            cargo build -p atuin-server --locked --release

  unit-test:
    strategy:
      matrix:
        os: [depot-ubuntu-24.04, depot-macos-26, depot-windows-2025-16]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - name: Install OpenSSL dev libraries (Linux)
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@v1.6.3
        with:
          packages: libssl-dev pkg-config
          version: 1.0

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.98.0

      - uses: taiki-e/install-action@v2
        name: Install nextest
        with:
          tool: cargo-nextest

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
             ~/.cargo/git
             target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo test
        run: cargo nextest run --lib --bins

  check:
    strategy:
      matrix:
        os: [depot-ubuntu-24.04, depot-macos-26, depot-windows-2025-16]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - name: Install OpenSSL dev libraries (Linux)
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@v1.6.3
        with:
          packages: libssl-dev pkg-config
          version: 1.0

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.98.0

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
             ~/.cargo/git
             target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo check (all features)
        run: cargo check --all-features --workspace

      - name: Run cargo check (no features)
        run: cargo check --no-default-features --workspace

      - name: Run cargo check (sync)
        run: cargo check --no-default-features --features sync --workspace

      - name: Run cargo check (server)
        run: cargo check -p atuin-server

      - name: Run cargo check (client only)
        run: cargo check --no-default-features --features client --workspace

  integration-test:
    runs-on: depot-ubuntu-24.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: atuin
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: atuin
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v7

      - name: Install OpenSSL dev libraries (Linux)
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@v1.6.3
        with:
          packages: libssl-dev pkg-config
          version: 1.0

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.98.0

      - uses: taiki-e/install-action@v2
        name: Install nextest
        with:
          tool: cargo-nextest

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
             ~/.cargo/git
             target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo test
        run: cargo nextest run --test '*'
        env:
          ATUIN_DB_URI: postgres://atuin:pass@localhost:5432/atuin

  clippy:
    runs-on: depot-ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: Install OpenSSL dev libraries (Linux)
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@v1.6.3
        with:
          packages: libssl-dev pkg-config
          version: 1.0

      - name: Install latest rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.98.0
          components: clippy

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Run clippy (tests)
        run: cargo clippy --tests -- -D warnings

  docs:
    runs-on: depot-ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: Install OpenSSL dev libraries (Linux)
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@v1.6.3
        with:
          packages: libssl-dev pkg-config
          version: 1.0

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.98.0

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-doc-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo doc
        run: cargo doc --document-private-items --no-deps --workspace
        env:
          RUSTDOCFLAGS: -D warnings

  format:
    runs-on: depot-ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: Install nightly rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - name: Format
        run: cargo +nightly fmt -- --check

  deny:
    runs-on: depot-ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check

  package:
    runs-on: depot-ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.98.0

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-package-${{ hashFiles('**/Cargo.lock') }}

      - name: Build packaged tarballs
        run: |
          rm -rf ~/.cargo/registry/{cache,src}/*/atuin*
          rm -rf target/package
          rm -rf target/{debug,release}/libatuin*.rlib
          rm -rf target/{debug,release}/deps/libatuin*
          rm -rf target/{debug,release}/.fingerprint/atuin*
          cargo package --workspace
