name: Shellcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: depot-ubuntu-24.04

    steps:
    - uses: actions/checkout@v7
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@2.0.0
      env:
        SHELLCHECK_OPTS: "-e SC2148"
