//! Regenerates atuin-api-client's `src/generated.rs` from its `openapi.json`.
//!
//! `cargo run --locked --manifest-path crates/atuin-api-client/codegen/Cargo.toml` rewrites the
//! file in place. The output is byte-deterministic, so CI reruns the generator and fails on a diff.

use std::path::{Path, PathBuf};
use std::process::ExitCode;
use std::{fs, io};

use progenitor::Generator;
use serde_json::Value;

mod mapping;
mod prepare;

use mapping::SpecError;

const HEADER: &str =
    "// @generated by crates/atuin-api-client/codegen from openapi.json. Do not edit.\n\n";

#[derive(Debug, thiserror::Error)]
enum CodegenError {
    #[error("{}: {source}", path.display())]
    Io {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
    #[error("openapi.json is not an OpenAPI 3.0 document: {0}")]
    Json(#[from] serde_json::Error),
    #[error(transparent)]
    Spec(#[from] SpecError),
    #[error("progenitor rejected the spec: {0}")]
    Progenitor(#[from] progenitor::Error),
    #[error("progenitor emitted code syn cannot parse: {0}")]
    Syntax(#[from] syn::Error),
}

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(err) => {
            eprintln!("error: {err}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), CodegenError> {
    let crate_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the generator lives inside the crate it generates");
    let spec_path = crate_dir.join("openapi.json");
    let out_path = crate_dir.join("src").join("generated.rs");

    let spec = fs::read(&spec_path).map_err(|source| CodegenError::Io {
        path: spec_path,
        source,
    })?;
    let code = generate(&spec)?;
    fs::write(&out_path, code).map_err(|source| CodegenError::Io {
        path: out_path,
        source,
    })
}

/// Generate the client's Rust source from the bytes of `openapi.json`.
fn generate(spec: &[u8]) -> Result<String, CodegenError> {
    let mut spec: Value = serde_json::from_slice(spec)?;
    prepare::strip(&mut spec)?;
    mapping::check(&spec)?;

    let spec: openapiv3::OpenAPI = serde_json::from_value(spec)?;
    let tokens = Generator::new(&mapping::settings()).generate_tokens(&spec)?;
    Ok(format!("{HEADER}{}", prettyplease::unparse(&syn::parse2(tokens)?)))
}

#[cfg(test)]
mod tests {
    use rstest::{fixture, rstest};
    use serde_json::{Value, json};

    use super::generate;

    /// The hub's spec, as checked in next to the generated client.
    #[fixture]
    fn spec() -> Value {
        serde_json::from_str(include_str!("../../openapi.json")).expect("openapi.json is JSON")
    }

    fn generate_from(spec: &Value) -> String {
        generate(&serde_json::to_vec(spec).expect("a JSON value serializes"))
            .expect("the spec generates")
    }

    fn set(spec: &mut Value, pointer: &str, value: Value) {
        *spec.pointer_mut(pointer).expect("the pointer names an existing value") = value;
    }

    #[rstest]
    fn generation_is_deterministic(spec: Value) {
        assert_eq!(generate_from(&spec), generate_from(&spec));
    }

    #[rstest]
    #[case::secret_body_field("pub password: crate::Secret,")]
    #[case::secret_query_parameter("code: &'a crate::Secret,")]
    #[case::unsigned_count("count: &'a u64,")]
    #[case::date_time("pub resets_at: crate::DateTime,")]
    #[case::presigned_url("pub upload_url: ::url::Url,")]
    #[case::record_replacement(
        "::atuin_domain::record::Record<::atuin_domain::record::EncryptedData>,"
    )]
    #[case::status_replacement("ResponseValue<::atuin_domain::record::RecordStatus>")]
    fn mapped_schemas_generate_their_target_type(spec: Value, #[case] expected: &str) {
        let code = generate_from(&spec);
        assert!(code.contains(expected), "generated code lacks {expected:?}");
    }

    #[rstest]
    #[case::typed_error_bodies("Error<types::")]
    #[case::capabilities_known_parameter("x_atuin_capabilities_known")]
    #[case::chrono("chrono")]
    fn stripped_and_unmapped_shapes_never_reach_the_code(spec: Value, #[case] absent: &str) {
        let code = generate_from(&spec);
        assert!(!code.contains(absent), "generated code contains {absent:?}");
    }

    /// The version of `package` that `lock`, a Cargo.lock, pins, e.g. `0.15.0`.
    fn locked<'a>(lock: &'a str, package: &str) -> Option<&'a str> {
        let entry = format!("name = \"{package}\"\nversion = \"");
        let version = &lock[lock.find(&entry)? + entry.len()..];
        version.split('"').next()
    }

    /// The generated code calls into the runtime's progenitor-client, which breaks on progenitor's
    /// minor version: the generator's lockfile and atuin's must agree on it.
    #[rstest]
    fn the_generator_matches_the_runtime_client() {
        let generator = locked(include_str!("../Cargo.lock"), "progenitor-impl")
            .expect("the generator locks progenitor-impl");
        let runtime = locked(include_str!("../../../../Cargo.lock"), "progenitor-client")
            .expect("atuin locks progenitor-client");
        let minor = |version: &'static str| version.rsplit_once('.').map(|(minor, _patch)| minor);

        assert_eq!(minor(generator), minor(runtime));
    }

    #[rstest]
    fn a_nullable_secret_stays_a_secret(mut spec: Value) {
        set(
            &mut spec,
            "/components/schemas/LoginRequest/properties/password",
            json!({"type": "string", "format": "password", "nullable": true}),
        );
        let code = generate_from(&spec);
        assert!(code.contains("pub password: ::std::option::Option<crate::Secret>,"));
    }
}
